- hosts: centos3
  tasks: 
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: install the latest version of Apache
      yum:
        name: httpd
        state: latest

    - name: Start and enable Apache
      systemd:
        state: started
        enabled: yes
        name: httpd
        
    - name: Download foo.conf
      get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page294/woody.zip
        dest: /tmp/

    - name: install unzip
      yum:
        name: unzip
        state: latest

    - name: Ensure /var/www/html is not a file
      file:
        path: /var/www/html
        state: absent
      when: "'/var/www/html' is file"

    - name: Ensure /var/www/html is a directory
      file:
        path: /var/www/html
        state: directory

  
    - name: Unarchive a file that is already on the remote machine
      unarchive:  
        src: /tmp/woody.zip
        dest: /var/www/html
        remote_src: yes

    - name: Move Template Files
      shell: mv /var/www/html/carpenter-website-template/*  /var/www/html
      args: 
        creates: /var/www/html/index.html


    - name: Recursively change ownership of a directory
      file:
        path: /var/www/html
        state: directory
        recurse: yes
        owner: apache
        group: apache